global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.163.com:465'
  smtp_from: ''    #CHANGEME（发送方邮箱地址）
  smtp_auth_username: ''    #CHANGEME（发送方邮箱地址）
  smtp_auth_password: ''    #CHANGEME（发送方邮箱授权码，163 邮箱可设置）
  smtp_require_tls: false
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 10m
  receiver: 'email'
templates:
  - 'templates/*.tmpl'
receivers:
  - name: 'email'
    email_configs:
      - to: ''    #CHANGEME（接收方邮箱地址）
        html: '{{ template "email.html" . }}'
        headers:
          Subject: "[WARN] 报警邮件 {{ .CommonLabels.instance }} {{ .CommonAnnotations.summary }}"
  #- name: 'web.hook'
  #  webhook_configs:
  #    - url: 'http://127.0.0.1:5001/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
